%YAML:1.0
---
Middle_Line:
        [
                { x: 9.767, y: -13.0, z: 0.3 },
                { x: 10.168, y: -5.529, z: 0.3 },
                { x: 12.902, y: -1.982, z: 0.3 },
                { x: 17.863, y: -2.548, z: 0.3 },
                { x: 17.832, y: -9.471, z: 0.3 },
                { x: 15.098, y: -13.018, z: 0.3 }
        ]
Left_Road:
        [

                { x: 20.35, y: -2.9, z: 0.3 },
                { x: 20.95, y: -3.33, z: 0.2 },
                { x: 24.32, y: -3.33, z: 0.2 },
                { x: 24.32, y: 0, z: 0.3 },
                { x: 13.6, y: 0, z: 0.3 },
                { x: 13.6, y: -1.8, z: 0.2 }
        ]
Right_Road:
        [
                { x: 25.04, y: -15, z: 1 },
                { x: 25.04, y: -12.5, z: 1 },
                { x: 25.04, y: -12.5, z: 0.3 },
                { x: 18.572, y: -12.5, z: 0.3 },
                { x: 17.402, y: -13.84, z: 0.3 },
                { x: 14.44, y: -13.84, z: 0.3 },
                { x: 13.82, y: -13.14, z: 0.3 },
                { x: 7.683, y: -13, z: 0.3 },
                { x: 10.0, y: -15, z: 0.3 },
                { x: 10.0, y: -15, z: 1 }
        ]
Enemy_Buff:
        [
                { x: 22.08, y: -10.932, z: 0.7 },
                { x: 22.08, y: -10.932, z: 1.4 },
                { x: 23.08, y: -12.3, z: 1.4 },
                { x: 23.08, y: -12.3, z: 0.6 },
                # { x: 18.44, y: -12.3, z: 0.6 },
                { x: 19.602, y: -12.3, z: 0.6 },
                # { x: 17.99, y: -11.913, z: 0.7 },
                { x: 18.99, y: -10.932, z: 0.7 }
        ]
Self_Fortress:
        [
                { x: 6.15443, y: -8.272, z: 0.0 },
                { x: 7.046, y: -8.272, z: 0.0 },
                { x: 7.491, y: -7.5, z: 0.0 },
                { x: 7.046, y: -6.728, z: 0.0 },
                { x: 6.15443, y: -6.728, z: 0.0 },
                { x: 5.7089, y: -7.5, z: 0.0 }
        ]
Enemy_Fortress:
        [
                { x: 21.965, y : -6.522, z : 0.15 },
                { x: 20.835, y : -6.522, z : 0.0 },
                { x: 20.271, y : -7.5, z : 0.0 },
                { x: 20.835, y : -8.478,  z : 0.0 },
                { x: 21.965, y : -8.478, z : 0.15 },
                { x: 22.529, y : -7.5, z : 0.2 }
        ]